name: Herring Cove
author: Herring Cove
baseurl: /herring-cove
description: theme for jekyll
github: http://www.github.com/radioku5e
twitter: http://www.twitter.com/ku5e
facebook: http://www.facebook.com/radioku5e
linkedin: http://www.linkedin.com/pub/mario-martinez-jr-mba
email: ku5e[at]ku5e.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
