name: KU5E
author: Mario Martinez
baseurl: http://www.ku5e.com
description: 
github: http://www.github.com/radioku5e
twitter: http://www.twitter.com/ku5e
facebook: http://www.facebook.com/radioku5e
linkedin: http://www.linkedin.com/pub/mario-martinez-jr-mba
email: ku5e[at]ku5e.com
location: 28.4158° N  81.2988° W
disqus: diqus-username

##Make sure to edit the abve fields, especially for disqus.
  
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
